baseurl= "http://13j-programmers.github.io/"
LanguageCode= "ja-JP"
Title= "Omatsuti People"
paginate = 5
DisqusShortname = "YOUR_SHORT_NAME_HERE"
Copyright = "All rights reserved - 2016"
canonifyurls = true

[params]
  description = "13J-Programmers"

  cover = "images/cover.jpg"

  author = "13J-programmers"
  authorlocation = "Nagano, Japan"
  authorwebsite = "http://13j-programmers.github.io/"

  bio= "National Insutitute of Technology, Nagano College"
  logo = "images/logo.png"

  googleAnalyticsUserID = "UA-79101-12"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  # RSSLink = "http://feeds.feedburner.com/..." 

  githubName = "13J-Programmers"

  # twitterName = ""
  # facebookName = ""
  # linkedinName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false

[[menu.main]]
  name = "My Blog"
  weight = -120
  identifier = "blog"
  url = "/"

[[menu.main]]
  name = "About us"
  weight = -110
  identifier = "about"
  url = "/about/"

[[menu.main]]
  name = "Products"
  weight = -110
  identifier = "product"
  url = "/product/"

[[menu.main]]
  name = "4.JS"
  weight = -110
  identifier = "4js"
  url = "/4J-Class-Project/"
